using DemoMicroService.AdministrationService.Samples;

namespace DemoMicroService.AdministrationService.EntityFrameworkCore.Applications;

public class EfCoreSampleAppServiceTests : SampleAppService_Tests<AdministrationServiceEntityFrameworkCoreTestModule>
{

}
