config:
  selfUrl: # https://gateway-public.demomicroservice.dev
  corsOrigins: # https://demomicroservice-st-gateway-web,https://demomicroservice-st-gateway-public-web
  authServer:
    authority: # http://demomicroservice-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.demomicroservice.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #

reRoutes:
  accountService:
    url: http://demomicroservice-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://demomicroservice-st-administration
  productService:
    url: http://demomicroservice-st-product

ingress:
  host: gateway-public.demomicroservice.dev
  tlsSecret: demomicroservice-tls

image:
  repository: mycompanyname/demomicroservice-gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    