config:
  selfUrl: # https://saas.demomicroservice.dev
  corsOrigins: https://demomicroservice-st-gateway-web,https://demomicroservice-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://demomicroservice-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.demomicroservice.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.demomicroservice.dev
  tlsSecret: demomicroservice-tls

image:
  repository: mycompanyname/demomicroservice-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      